### PR TITLE
#53 Improve how map is placed over the video

### PR DESCRIPTION
**Pull request by ptanov**

### CODE REVIEW

**Comment by time4tea** [comment]
Hey this is really nice! Thanks for the contribution. 

There are two things that I will add next - don't worry about doing them
1 - there are approval tests for images in the tests folder. Image approval tests that contain text and maps are extremely machine dependent, so really need to be regenerated for each person, but they are very helpful while working
2 - you have edited the "generated" documents not the source files. This is completely undocumented as it has been only me working on docs. The docs you have added are very good, but they will be overwritten when next docs are generated so I'll move the changes into the source. The figures in the docs are generated automatically from the source, using `make docs` or `make doc` can't remember right now, so we know that the example images will always match up with example code. See the source docs in `build-scripts/examples` - probably I should move them somewhere more obvious.

Once again, thanks for this, it's really nice.

**Comment by ptanov** [comment]
Happy to help with this!

Now I checked Makefile and I think it is pretty nice and self explanatory. I missed it because initially I made my changes on top of `venv/lib/python3.8/site-packages/gopro_overlay` just to try them and later I forked the repo just to contribute the changes (I don't have configured Python development environment on my computer).

Just ping me if I have to change something here (or in the rest of pull/merge requests).

**Comment by time4tea** [comment]
So - I did those two things. Hopefully this is OK? If so, I'll put the changes onto `main`

**Comment by ptanov** [comment]
Thanks!

**Pull request merged**
