### PR TITLE
Improved the backfill implementation for timeseries class

### LINKED ISSUE #3: Wrong speed incidation due to a bad timeseries' backfill implementation
image

I used GoPro Hero 7 camera for capturing video with GPS turned on. In addition to that, I also used the GPX recorder app (Android application) to record `*.gpx` files with a frequency of 1 second.

After doing some research I found that my gpx file contained the following lines:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.0" creator="GPX Recorder"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.topografix.com/GPX/1/0"
xsi:schemaLocation="http://www.topografix.com/GPX/1/0
http://www.topografix.com/GPX/1/0/gpx.xsd">
	<name>GPX</name>
	<trk><name>Track</name><number>1</number><trkseg>
		<trkpt lat="52.373556546481076" lon="4.88642354266687"><ele>45.50195328973657</ele><time>2021-11-17T10:42:11.000+01:00</time></trkpt>
		<trkpt lat="52.37353850317893" lon="4.886484720678822"><ele>45.42708020318395</ele><time>2021-11-17T10:42:12.000+01:00</time></trkpt>
		<trkpt lat="52.373522072418325" lon="4.88653858684518"><ele>45.17022492319613</ele><time>2021-11-17T10:42:12.999+01:00</time></trkpt>
		<trkpt lat="52.373508187525026" lon="4.886598841681643"><ele>45.11734786056542</ele><time>2021-11-17T10:42:13.999+01:00</time></trkpt>
	</trkseg></trk>
</gpx>
```

Apparently, the timer is not perfect in android and it can have some errors which in this case is -1 millisecond.

That however triggers backfilling procedure to start producing additional records with interpolated points. Since an interpolated geo point and a real one are going to be different anyways with the time difference of just 1 millisecond, the speed value at that point will be insane.

### PR DESCRIPTION
**Pull request by XAMeLeOH**
Resolves #3

### CODE REVIEW

**Review by time4tea — APPROVED** [review]
thanks for the contribution!

**Comment by time4tea** [comment]
Hmm. however, the tests don't pass... Please could you ensure that the behaviour didn't change in an unanticipated way. Thanks!

**Comment by XAMeLeOH** [comment]
Hi @time4tea!
Great catch! I fixed the issue you noticed and added a few more tests

**Comment by time4tea** [comment]
Thanks for contributing!

**Pull request merged**
