### PR TITLE
#57 Support timelapse/timewarp videos

### PR DESCRIPTION
**Pull request by ptanov**

### CODE REVIEW

**Comment by time4tea** [comment]
This is very interesting. Mostly this looks very useful, but I am not sure about the stepper starting at -ve time. This will i think cause desynchronised output with normal videos, as sometimes the metadata can start before the video. This is expected and there are various schemes in the code to figure out exactly how early the metadata starts.

**Comment by ptanov** [comment]
I see your point. I didn't realized that metadata may start earlier before the video (but it makes sense).
I reverted my changes for stepper starting at -ve time.
What do you think about adding a flag to enable `timelapse_correction` that will be disabled by default so we don't introduce regression (and brake the normal videos)?

**Comment by time4tea** [comment]
Please don't fix conflicts - I'm using this as a guide, but not quite implementing exactly the same as you did. Thanks for the contribution though. It is much appreciated!

**Comment by time4tea** [comment]
Thanks for your help with this. The changes are in 0.57.0

**Comment by ptanov** [comment]
Thank you!

**Pull request closed without merging**
